application:
    build: containers/code
    volumes:
        - www:/var/www
        - logs/laravel/:/var/www/storage/logs
    tty: true
db:
    image: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: laravel
        MYSQL_USER: root
        MYSQL_PASSWORD: root
php:
    build: containers/php-fpm
    expose:
        - 9000:9000
    volumes_from:
        - application
    links:
        - db
nginx:
    build: containers/nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - application
    volumes:
        - logs/nginx/:/var/log/nginx
